---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auth0-oidc-secret
  namespace: chuck-norris
spec:
  encryptedData:
    QUARKUS_OIDC_CREDENTIALS_SECRET: AgDE6TmLNpHuOV6RMIPYoZV/1VA4mXolwS19FGDyCpvuhGOGcA/w6CJkGZStgX0F1Qvb+4GrS93iETu0I1asOeB3bgNw7EO3ZsLLGhK4QbHqUt4NojgBW02ZmCQ08/aFtf5TFDKA25OWhgZuV3bid9akn68GmUDd3JM1sz8kFLfCvPJfb3CUdcLqp8Qv28QaNb7S82vhGiNh0NE0BaD3zKA4gKDEOQgQ5cGE3YuZn4/SdpfCw2ayL9Jks8nvI2jv2jdagJeDRYsjaH/sXeGo4FkP9xmcdKeNn2r9hcCEPz2fLxmfjYZQWAvys/AM30ZyGcFcGVsaosJ9htyUa1dq+Kk4mQaCg/WWGqQ6gOh0ttfDtDqYbQHJ8bNXkVhuUX+ekzPr1tAbBhChPMV6TOf9Z0OPAuCAiOkijFRTQ8jLUY/8AcNglnHMOSBrYID6R7CHBG26732VpvaT9x/WUCwIcvbhsiYjE/v8hnpMeTgTvPckwvdXxjSw1KtcrLGeh16R1gI6IxI8VQKtrYr63JtDamafzEhBV9V2NIY7pPAQYFaqMcMQHexwDLiJwCRx8KHoMoW09U0ZtXDRwTSLF0gEXhpaUdMx+Aio5Cn9HAczDxhYtNZ4m/TkKTdTxxYf7K0IiXqePgz6Gf4se1cL1xy2PgTJOs5ocawyOZNWULgUx9CAHrUwSpGTFQOnY2vG7KuOuj17PchwUUDTTl54mrUX2IOSD1mvigpnBfhXok4TU9ne4onGmDUgf4zwzujG4OZqwSHamdc3CGILdWjOjB3mw6wv
  template:
    metadata:
      creationTimestamp: null
      name: auth0-oidc-secret
      namespace: chuck-norris
