apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - auth0-sealed-secret.yaml
  - db-sealed-secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
